sudo: required
dist: "trusty"
os: "linux"


language: generic

# Caching so the next build will be fast too.

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'



install:
# Build dependencies
- sudo apt-get update -qq
- sudo apt-get install -q -y libsdl2-dev libsdl2-ttf-dev
- stack --no-terminal --install-ghc build

script:
# Build the package, its tests, and its docs and run the tests
  - stack --no-terminal test --haddock --no-haddock-deps
