sudo: required
dist: "trusty"
os: "linux"


language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
- sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots       # libsdl2
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies
- sudo apt-get update -qq
- sudo apt-get install -q -y libsdl2-dev libsdl2-ttf

script:
# Build the package, its tests, and its docs and run the tests
  - stack --no-terminal test --haddock --no-haddock-deps
